/* eslint-disable */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Send a message to Claude via a fresh sidecar process
 */
async sendAgentMessage(message: string, images: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_agent_message", { message, images }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the current session
 */
async clearAgentSession() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_agent_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current session ID
 */
async getSessionId() : Promise<string | null> {
    return await TAURI_INVOKE("get_session_id");
},
/**
 * Cancel the current query (drops stdin, causing process to exit)
 */
async stopSidecar() : Promise<void> {
    await TAURI_INVOKE("stop_sidecar");
},
/**
 * Quit the application
 */
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
/**
 * Check if running in dev mode
 */
async isDevMode() : Promise<boolean> {
    return await TAURI_INVOKE("is_dev_mode");
},
/**
 * Check if running in supiki mode
 */
async isSupikiMode() : Promise<boolean> {
    return await TAURI_INVOKE("is_supiki_mode");
},
/**
 * Answer an AskUserQuestion from the agent
 * questions_json is a JSON string of the questions array (to preserve exact structure)
 */
async answerAgentQuestion(questionId: string, questionsJson: string, answers: { [key in string]: string }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_agent_question", { questionId, questionsJson, answers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a base64-encoded image in the system's default image viewer
 * The base64 string should include the data URL prefix (e.g., "data:image/png;base64,...")
 */
async openImageInViewer(base64Data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_image_in_viewer", { base64Data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set custom working directory for sidecar
 * Also clears the session to start fresh with the new cwd
 */
async setSidecarCwd(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sidecar_cwd", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current sidecar working directory (custom setting only)
 */
async getSidecarCwd() : Promise<string | null> {
    return await TAURI_INVOKE("get_sidecar_cwd");
},
/**
 * Get actual working directory (custom if set, otherwise app's cwd)
 */
async getActualCwd() : Promise<string> {
    return await TAURI_INVOKE("get_actual_cwd");
},
/**
 * Get recent working directories
 */
async getRecentCwds() : Promise<string[]> {
    return await TAURI_INVOKE("get_recent_cwds");
},
/**
 * Open native folder picker dialog
 */
async pickFolder() : Promise<string | null> {
    return await TAURI_INVOKE("pick_folder");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/



/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
